use serde::{Deserialize, Serialize};

use super::schema::{AIProviderKind, AIProviderPresetId};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AIExtraBodyStrategy {
    None,
    Generic,
    DeepSeekThinking,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AIProviderPreset {
    pub id: AIProviderPresetId,
    pub label: &'static str,
    pub provider_kind: AIProviderKind,
    pub default_base_url: &'static str,
    pub default_chat_path: &'static str,
    pub default_model: &'static str,
    pub api_key_env_hint: &'static str,
    pub supports_response_format: bool,
    pub supports_json_mode: bool,
    pub supports_thinking: bool,
    pub supports_reasoning_effort: bool,
    pub extra_body_strategy: AIExtraBodyStrategy,
    pub docs_url: Option<&'static str>,
}

pub fn all_provider_presets() -> Vec<AIProviderPreset> {
    vec![
        AIProviderPreset {
            id: AIProviderPresetId::DeepSeek,
            label: "DeepSeek，推荐",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "https://api.deepseek.com",
            default_chat_path: "/chat/completions",
            default_model: "deepseek-v4-flash",
            api_key_env_hint: "DEEPSEEK_API_KEY",
            supports_response_format: true,
            supports_json_mode: true,
            supports_thinking: true,
            supports_reasoning_effort: true,
            extra_body_strategy: AIExtraBodyStrategy::DeepSeekThinking,
            docs_url: Some("https://api-docs.deepseek.com/"),
        },
        AIProviderPreset {
            id: AIProviderPresetId::Kimi,
            label: "Kimi / Moonshot",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "https://api.moonshot.cn/v1",
            default_chat_path: "/chat/completions",
            default_model: "kimi-k2.7-code-highspeed",
            api_key_env_hint: "MOONSHOT_API_KEY",
            supports_response_format: true,
            supports_json_mode: true,
            supports_thinking: false,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::Generic,
            docs_url: Some("https://platform.moonshot.cn/docs"),
        },
        AIProviderPreset {
            id: AIProviderPresetId::QwenDashScope,
            label: "通义千问 / DashScope",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
            default_chat_path: "/chat/completions",
            default_model: "qwen-plus",
            api_key_env_hint: "DASHSCOPE_API_KEY",
            supports_response_format: false,
            supports_json_mode: true,
            supports_thinking: false,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::Generic,
            docs_url: Some("https://help.aliyun.com/zh/dashscope/"),
        },
        AIProviderPreset {
            id: AIProviderPresetId::ZhipuGlm,
            label: "智谱 GLM",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "https://open.bigmodel.cn/api/paas/v4",
            default_chat_path: "/chat/completions",
            default_model: "glm-4.5",
            api_key_env_hint: "ZHIPUAI_API_KEY",
            supports_response_format: false,
            supports_json_mode: true,
            supports_thinking: false,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::Generic,
            docs_url: Some("https://docs.bigmodel.cn/"),
        },
        AIProviderPreset {
            id: AIProviderPresetId::Minimax,
            label: "MiniMax",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "https://api.minimax.chat/v1",
            default_chat_path: "/chat/completions",
            default_model: "",
            api_key_env_hint: "MINIMAX_API_KEY",
            supports_response_format: false,
            supports_json_mode: true,
            supports_thinking: false,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::Generic,
            docs_url: Some("https://platform.minimaxi.com/document"),
        },
        AIProviderPreset {
            id: AIProviderPresetId::Baichuan,
            label: "百川",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "",
            default_chat_path: "/chat/completions",
            default_model: "",
            api_key_env_hint: "BAICHUAN_API_KEY",
            supports_response_format: false,
            supports_json_mode: true,
            supports_thinking: false,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::Generic,
            docs_url: None,
        },
        AIProviderPreset {
            id: AIProviderPresetId::DoubaoArk,
            label: "豆包 / 火山方舟",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "https://ark.cn-beijing.volces.com/api/v3",
            default_chat_path: "/chat/completions",
            default_model: "",
            api_key_env_hint: "ARK_API_KEY",
            supports_response_format: false,
            supports_json_mode: true,
            supports_thinking: false,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::Generic,
            docs_url: Some("https://www.volcengine.com/docs/82379"),
        },
        AIProviderPreset {
            id: AIProviderPresetId::Siliconflow,
            label: "硅基流动",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "https://api.siliconflow.cn/v1",
            default_chat_path: "/chat/completions",
            default_model: "",
            api_key_env_hint: "SILICONFLOW_API_KEY",
            supports_response_format: false,
            supports_json_mode: true,
            supports_thinking: false,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::Generic,
            docs_url: Some("https://docs.siliconflow.cn/"),
        },
        AIProviderPreset {
            id: AIProviderPresetId::CustomOpenAICompatible,
            label: "自定义 OpenAI-compatible",
            provider_kind: AIProviderKind::OpenAICompatible,
            default_base_url: "",
            default_chat_path: "/chat/completions",
            default_model: "",
            api_key_env_hint: "OPENAI_COMPATIBLE_API_KEY",
            supports_response_format: false,
            supports_json_mode: true,
            supports_thinking: false,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::Generic,
            docs_url: None,
        },
        AIProviderPreset {
            id: AIProviderPresetId::Ollama,
            label: "Ollama 本地模型",
            provider_kind: AIProviderKind::Ollama,
            default_base_url: "http://localhost:11434",
            default_chat_path: "/api/chat",
            default_model: "qwen3:8b",
            api_key_env_hint: "",
            supports_response_format: false,
            supports_json_mode: true,
            supports_thinking: true,
            supports_reasoning_effort: false,
            extra_body_strategy: AIExtraBodyStrategy::None,
            docs_url: Some("https://github.com/ollama/ollama/blob/main/docs/api.md"),
        },
    ]
}

pub fn provider_preset(id: AIProviderPresetId) -> Option<AIProviderPreset> {
    all_provider_presets()
        .into_iter()
        .find(|preset| preset.id == id)
}
